algoritmo "Algoritmo13"
var
   cont, dolar, reais, limite: real
inicio
   cont <- 0
   
   escreva("Digite o valor do limite: ")
   leia(limite)
   
   escreval()
   
   enquanto cont < limite faca
      cont <- cont + 1

      escreva("Digite o valor da moeda em reais: ")
      leia(reais)

      dolar <- reais / 2.2
      escreval("O valor de real para dolar eh: ", dolar)
   fimenquanto
fimalgoritmo
