algoritmo "Exerc.29"
var
    nota1, nota2, nota3, nota4: real
inicio
    escreva("Digite a primeira nota: ")
    leia(nota1)
    limpatela()
    escreva("Digite a segunda nota: ")
    leia(nota2)
    limpatela()
    escreva("Digite a terceira nota: ")
    leia(nota3)
    limpatela()
    escreva("Digite a quarta nota: ")
    leia(nota4)
    limpatela()
    escreva("A média aritmética encontrada foi: ", ((nota1+nota2+nota3+nota4)/4))
fimalgoritmo
