algoritmo "Algoritmo28"
var
   valor1: inteiro
   valor2: inteiro
   valor3: inteiro
   soma: real
inicio
      escreva("Digite o primeiro valor: ")
      leia(valor1)
      escreva("Digite o segundo valor: ")
      leia(valor2)
      escreva("Digite o terceiro valor: ")
      leia(valor3)
      soma <- (valor1 ^ 2) + (valor2 ^ 2)+(valor3 ^ 2)
      escreva("O resultado da soma dos tres valores eh: ", soma)
fimalgoritmo
