algoritmo "Algoritmo29"
var
   nota1, nota2, nota3, nota4: inteiro
   ma: real
   
inicio
      escreva("Digite o valor da nota 1: ")
      leia(nota1)
      escreva("Digite o valor da nota 2: ")
      leia(nota2)
      escreva("Digite o valor da nota 3: ")
      leia(nota3)
      escreva("Digite o valor da nota 4: ")
      leia(nota4)
      ma <- (nota1 + nota2 + nota3 + nota4) / 4
      escreva("A Media Aritmetica das quatro notas eh: ", ma)
fimalgoritmo
