algoritmo "Algoritmo15"
var
   num: inteiro
inicio
   escreva("Digite um numero: ")
   leia(num)
   
   escolha num
      caso 1
         escreva("Domingo")
      caso 2
         escreva("Segunda")
      caso 3
         escreva("Terca")
      caso 4
         escreva("Quarta")
      caso 5
         escreva("Quinta")
      caso 6
         escreva("Sexta")
      caso 7
         escreva("Sabado")
      outrocaso
         escreva("Valor invalido")
   
   fimescolha
fimalgoritmo
